lidemeng99/AppPortal

pages/personalpage/personalpage-detail.html

Vue Update

---

dist/builds.js

Update Builds.js File （remove alert(url+"haha");

Update builds.js File

---

assets/src/portal/components/personalpagesearch.vue

personalpagesearch.vue

---

pages/personalpage/personalpage-detail.html
pages/personalpage/personalpage-list.html

set <base href="http://172.16.51.144/"/>

set <base href="http://172.16.51.144/"/>

---

assets/css/personalpage/personalpage.css
assets/css/personalpage/personalpagesearch.css
dist/portUrlVue.js
pages/personalpage/personalpage-detail.html
pages/personalpage/personalpage-list-search.html
pages/personalpage/personalpage-list.html

personalpage add Header & footer

personalpage add Header & footer

---

pages/portal/workspace.html

Update refer Path of workspace.html

Update refer Path of workspace.html

---

src/schedule/all.js
src/schedule/eventservice.js
src/schedule/leader.js
src/schedule/personal.js
src/schedule/team.js

日程用户名修改20160804：

---

pages/portal/news_detail.html
src/portal/newsService.js
src/portal/news_detail.js

首页新闻详情提交20160808：

---

assets/libs/workspace/workspacePopView.js

Remove Alert at workspace.html

Remove Alert

---

assets/css/portal/portal-iframe.css
pages/portal/portal-index-iframe.html

Add iframe model

---

pages/portalManage/component.html

门户管理修改20160811：

---

pages/portal/news_more.html
pages/portal/news_search.html

更多、搜索样式修改20160812：

---

pages/portal/news_detail.html

新闻详情附件修改20160812：

---

pages/portal/news_detail.html

新闻详情图片修改20160812：

---

pages/portal/news_detail.html
pages/portal/news_more.html
pages/portal/news_search.html
pages/portalManage/column.html
pages/portalManage/style.html
src/portal/newsService.js
src/portal/news_detail.js
src/portalManage/columnAdmin.js
src/portalManage/styleAdmin.js

门户管理修改20160812：

---

src/portal/newsService.js
src/portalManage/portalservice.js

门户管理、门户新闻详情URL修改20160815：

---

src/portal/newsService.js
src/portalManage/columnAdmin.js
src/portalManage/componentAdmin.js
src/portalManage/portalAdmin.js
src/portalManage/portalservice.js
src/portalManage/styleAdmin.js
src/schedule/all.js
src/schedule/eventservice.js
src/schedule/leader.js
src/schedule/personal.js
src/schedule/team.js

门户管理、新闻详情URL、APIKEY修改20160815：

---

assets/libs/personalpage/contact.js
assets/libs/personalpage/contactMembers.js
assets/libs/personalpage/contactSameOrgInit.js
assets/libs/workspace/personalCon.js
assets/libs/workspace/workspacePopView.js
dist/main.js
dist/personalPageSearch.js
dist/webconfig.json
pages/personalpage/personalpage-detail.html
pages/personalpage/personalpage-list-search.html
pages/personalpage/personalpage-list.html
pages/portal/workspace.html

personalPagle UI/URL Path Update

personalPagle UI/URL Path Update

---

pages/portalManage/portal.html
pages/portalManage/style.html
src/portalManage/columnAdmin.js
src/portalManage/componentAdmin.js
src/portalManage/portalAdmin.js
src/portalManage/portalservice.js
src/portalManage/styleAdmin.js

样式添加修改20160815：

---

pages/portal/news_detail.html
pages/portalManage/component.html
src/portal/newsService.js
src/portal/news_detail.js
src/portalManage/componentAdmin.js
src/portalManage/styleAdmin.js

1、门户管理栏目新增更多值修改；
2、首页详情PDF预览修改；

门户管理修改20160815：

---

dist/webconfig.json

1、webcongif.json文件url、apikey修改；

webconfig文件修改LCM20160816：

---

pages/portal/portal-index-iframe.html

iframe修改20160816：

---

assets/css/portal/portal-iframe.css
pages/portal/portal-index-iframe.html
pages/portalManage/column.html
pages/portalManage/component.html
pages/portalManage/style.html
pages/schedule/all.html
pages/schedule/leader.html
pages/schedule/personal.html
pages/schedule/team.html

日程、门户管理头部修改20160817；

---

src/schedule/eventservice.js

日程url、apikey修改20160817:

---

pages/schedule/all.html
pages/schedule/leader.html
pages/schedule/personal.html

日程管理修改20160817：

---

src/schedule/all.js
src/schedule/leader.js
src/schedule/personal.js
src/schedule/team.js

日程修改20160817：

---

assets/libs/personalpage/contact.js
assets/libs/personalpage/contactMembers.js
assets/libs/personalpage/portUrl.js
assets/libs/workspace/personalCon.js
assets/libs/workspace/workspacePopView.js
pages/personalpage/personalpage-detail.html
pages/personalpage/personalpage-list-search.html
pages/personalpage/personalpage-list.html
pages/portal/workspace.html

Update UI/Default Value

---

pages/portal/news_detail.html
src/portal/news_detail.js

新闻详情播放MP4文件20160817：

---

assets/css/portal/portal-iframe.css
assets/libs/personalpage/contactMembers.js
pages/portal/portal-index-iframe.html
pages/portalManage/column.html
pages/portalManage/component.html
pages/portalManage/portal.html
pages/portalManage/style.html
pages/schedule/event-add.html
pages/schedule/event-edit.html
src/schedule/all.js
src/schedule/eventservice.js
src/schedule/leader.js
src/schedule/personal.js

日程修改20160818：

---

pages/portalManage/component.html
pages/portalManage/portal.html
pages/portalManage/style.html
pages/portalManage/tmp_navigation.html
pages/schedule/all.html
pages/schedule/leader.html
pages/schedule/personal.html
src/portalManage/styleAdmin.js

门户管理修改20160819：

---

pages/portal/index.html
pages/portal/news_more.html
pages/portal/news_search.html
src/portal/news_more.js
src/portal/news_search.js
src/schedule/all.js
src/schedule/eventservice.js
src/schedule/fullcalendar.js
src/schedule/leader.js

日程、更多Bug修改20160826：

---

assets/libs/workspace/personalCon.js
assets/libs/workspace/workspacePopView.js
pages/portal/workspace.html
src/portal/news_publish.js
src/schedule/fullcalendar.js
src/schedule/personal.js

1、工作台跳转督办加id;
2、日程按周浏览样式bug修改；
3、新增远程发布；

bug修改20160902；

---

pages/portal/news_publish.html
pages/portal/portal-index-iframe.html
pages/portalManage/portal.html
src/portal/news_publish.js

远程投稿修改20160910：

---

assets/libs/personalpage/contact.js
assets/libs/workspace/personalCon.js
pages/portalManage/portal.html
pages/schedule/all.html
pages/schedule/event-add.html
pages/schedule/event-edit.html
pages/schedule/leader.html
pages/schedule/personal.html
src/portalManage/portalAdmin.js
src/schedule/all.js
src/schedule/eventservice.js
src/schedule/leader.js
src/schedule/personal.js

1、新增日程时间可选bug修改；
2、新建、修改门户添加优先级字段；
3、其他bug修改；

bug修改20160913：

---

assets/css/personalpage/personalpage.css

个人页面样式调整20160914：
